In [160]:
import numpy as np

# Numpy array

In [161]:
np_vector = np.array([1, 2, 3])
print(np_vector)
print(type(np_vector))
print(np_vector.shape)

[1 2 3]
<class 'numpy.ndarray'>
(3,)


In [162]:
np_matrix = np.array([
    [1, 2, 3,],
    [8, 3, 1],
])

print(np_matrix)
print(np_matrix.shape)

[[1 2 3]
 [8 3 1]]
(2, 3)


In [163]:
np_cube = np.array([
    [[1, 2], [3, 2], [3, 8]],
    [[0, 1], [9, 7], [3, 4]],
])

print(np_cube)
print(np_cube.shape)

[[[1 2]
  [3 2]
  [3 8]]

 [[0 1]
  [9 7]
  [3 4]]]
(2, 3, 2)


In [164]:
np_vector = np.zeros((4, ))
print(np_vector)
print(np_vector.shape)

[0. 0. 0. 0.]
(4,)


In [165]:
np_vector = np.ones((4, ))
print(np_vector)
print(np_vector.shape)

[1. 1. 1. 1.]
(4,)


In [166]:
np_vector = np.full((4, ), 111)
print(np_vector)
print(np_vector.shape)

[111 111 111 111]
(4,)


In [167]:
unit_matrix = np.eye((4))
print(unit_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [168]:
np_vector = np.arange(1, 22, 3)
print(np_vector)

[ 1  4  7 10 13 16 19]


# Indexing and slicing

In [169]:
np_matrix = np.array([
    [1, 2, 3],
    [9, 7, 0]
])

print(np_matrix)
print(np_matrix.shape)

print(np_matrix[0, :2])
print(np_matrix[:, 0])
print(np_matrix[-1])
print(np_matrix[-1, :2])

[[1 2 3]
 [9 7 0]]
(2, 3)
[1 2]
[1 9]
[9 7 0]
[9 7]


In [170]:
print(np_matrix[:1, :2])
print(np_matrix[:1, :2].shape)

[[1 2]]
(1, 2)


In [171]:
np_matrix = np.random.random((4, 6))
print(np_matrix.shape)
print(np_matrix)

(4, 6)
[[0.36504996 0.51933775 0.32209098 0.41096837 0.39619372 0.32085666]
 [0.08993296 0.64085621 0.24320586 0.54049662 0.32667693 0.09179414]
 [0.17596572 0.94203381 0.70955514 0.91396828 0.4092866  0.98901807]
 [0.22656117 0.80486187 0.19677536 0.56187138 0.53189286 0.61791135]]


In [172]:
print(np_matrix[0:1].shape)
print(np_matrix[0:1])

(1, 6)
[[0.36504996 0.51933775 0.32209098 0.41096837 0.39619372 0.32085666]]


In [173]:
print(np_matrix[0:1][-1].shape)
print(np_matrix[0:1][-1])

(6,)
[0.36504996 0.51933775 0.32209098 0.41096837 0.39619372 0.32085666]


In [174]:
print(np_matrix[0:1][-1][1:3])

[0.51933775 0.32209098]


# Broadcasting

In [175]:
np_vector = np.array([1, 2, 3])
np_vector = np_vector + 3
print(np_vector)

[4 5 6]


In [176]:
np_matrix = np.array([
    [4, 5, 6],
    [7, 8, 9],
])

print(np_matrix*2)

[[ 8 10 12]
 [14 16 18]]


In [177]:
np_vector_range = np.arange(0, 20, 3)
print(np_vector_range)
print(np_vector_range*3)

[ 0  3  6  9 12 15 18]
[ 0  9 18 27 36 45 54]


In [178]:
a = np.ones((3, 5))
print(f"a: {a}")
b = np.arange(5)
print(f"b: {b}")
print(a + b)

a: [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
b: [0 1 2 3 4]
[[1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]]


In [179]:
a_new = np.arange(5)
print(a_new.shape)
a_new = a_new.reshape(5, 1)
print(a_new.shape)
print(a_new)

b_new = np.arange(5)
print(b_new.shape)
print(b_new)

c_new = a_new + b_new
print(c_new.shape)
print(c_new)

(5,)
(5, 1)
[[0]
 [1]
 [2]
 [3]
 [4]]
(5,)
[0 1 2 3 4]
(5, 5)
[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


# Iterator

In [180]:
np_vector = np.random.random(5, )
print(np_vector)
for x in np.nditer(np_vector):
    print(x)

[0.30437131 0.92031325 0.61339769 0.02362513 0.44160024]
0.30437131171981013
0.9203132467689978
0.6133976861561751
0.023625132104589164
0.44160023522715486


In [181]:
np_matrix = np.random.random((2, 3))
print(np_matrix)
for x in np.nditer(np_matrix):
    print(x)

[[0.98656771 0.09443934 0.86657902]
 [0.39283631 0.53110532 0.10221561]]
0.9865677098435194
0.09443934155917999
0.8665790218354043
0.3928363132808118
0.5311053218347702
0.10221561284435665


In [182]:
np_cube = np.random.random((2, 2, 2))
print(np_cube)
for x in np.nditer(np_cube):
    print(x)

[[[0.23673502 0.75391904]
  [0.07140061 0.88435549]]

 [[0.13678582 0.60136676]
  [0.93335403 0.83066129]]]
0.2367350186194923
0.7539190405633613
0.07140060811507642
0.8843554921598882
0.13678582012340235
0.6013667632535014
0.9333540333368814
0.8306612852327329


In [183]:
np_matrix = np.random.random((2, 3))
print(np_matrix)
for x in np.nditer(np_matrix, flags=["external_loop"], order='F'):
    print(x)

[[0.65651645 0.18025096 0.66308776]
 [0.90648429 0.72000257 0.07201235]]
[0.65651645 0.90648429]
[0.18025096 0.72000257]
[0.66308776 0.07201235]


In [184]:
for x in np.nditer(np_matrix, flags=["external_loop"], order='C'):
    print(x)

[0.65651645 0.18025096 0.66308776 0.90648429 0.72000257 0.07201235]


# Change size of array

In [185]:
a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
])
print(a.shape)

(2, 4)


In [186]:
b = a.reshape(4, 2)
print(b)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [187]:
np_cube = np.random.random((2, 2, 2))
print(np_cube)
print(np_cube.shape)

[[[0.73665926 0.83347398]
  [0.35277197 0.66503393]]

 [[0.6012553  0.99176022]
  [0.12878569 0.97800519]]]
(2, 2, 2)


In [188]:
tmp = np_cube.flatten()
print(tmp)
print(tmp.shape)

[0.73665926 0.83347398 0.35277197 0.66503393 0.6012553  0.99176022
 0.12878569 0.97800519]
(8,)


In [189]:
a_test = np.array([
    [1, 2],
    [4, 5],
])
print(a_test.shape)
b_test = np.expand_dims(a_test, axis=0)
print(b_test.shape)
print(b_test)

(2, 2)
(1, 2, 2)
[[[1 2]
  [4 5]]]


In [190]:
np_cube = np.random.random((1, 2, 2, 1))
print(np_cube)
result = np.squeeze(np_cube, axis=0)
print(result)
print(result.shape)

[[[[0.00102455]
   [0.61986743]]

  [[0.44892299]
   [0.84268625]]]]
[[[0.00102455]
  [0.61986743]]

 [[0.44892299]
  [0.84268625]]]
(2, 2, 1)


# Transpose

In [191]:
np_matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
])
print(np_matrix.shape)
print(np_matrix.T)
print(np_matrix.T.shape)

(2, 4)
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
(4, 2)


# Products

In [193]:
a = np.array([
    [1, 2, 3],
    [3, 1, 0],
])

b = np.array([
    [2, 1, 3],
    [1, 3, 4],
    [3, 1, 0],
])

print(a.dot(b))

[[13 10 11]
 [ 7  6 13]]


In [194]:
a = np.array([1, 2, 3])

b = np.array([3, 4, 5])

print(np.inner(a, b))

26


In [195]:
A = np.array([
    [2, 0, 6],
    [1, -1, 2],
])
B = np.array([
    [8, -3, 2],
    [4, 1, -5]
])

print(np.tensordot(A, B))

21


# Norms

In [198]:
A = np.array([1, 2, 3])
print(np.linalg.norm(A))

3.7416573867739413


In [200]:
print(np.linalg.norm(A, ord=1))

6.0
